version: 2

release:
  prerelease: auto
  draft: false

env:
  - CGO_ENABLED=0

builds:
  - id: linux-build
    dir: ./cmd/grype
    binary: grype
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    mod_timestamp: &build-timestamp '{{ .CommitTimestamp }}'
    ldflags: &build-ldflags |
      -w
      -s
      -extldflags '-static'
      -X main.version={{.Version}}
      -X main.gitCommit={{.Commit}}
      -X main.buildDate={{.Date}}
      -X main.gitDescription={{.Summary}}

  - id: darwin-build
    dir: ./cmd/grype
    binary: grype
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: *build-timestamp
    ldflags: *build-ldflags

  - id: windows-build
    dir: ./cmd/grype
    binary: grype
    goos:
      - windows
    goarch:
      - amd64
    mod_timestamp: *build-timestamp
    ldflags: *build-ldflags

archives:
  - id: linux-archives
    ids:
      - linux-build

  - id: darwin-archives
    ids:
      - darwin-build

  - id: windows-archives
    formats: [zip]
    ids:
      - windows-build

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

changelog:
  use: github
  sort: asc